server:
  port: 18081
spring:
  kafka:
    bootstrap-servers:
    producer: # producer ???
      bootstrap-servers:
      retries: 1 # ????
      acks: 1 # ????:??????????????????ack??
      batch-size: 16384 # ????
      buffer-memory: 33554432 # ????????
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #key??????
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #value??????
    consumer:
      bootstrap-servers:
      group-id: auto-dev #????
      #????: ??????????earliest?latest??????????????????
      # earliest?????????????
      #latest?????????????????????
      auto-offset-reset: earliest
      enable-auto-commit: false #?????????offset
      auto-commit-interval: 1S #??? enable-auto-commit=true????????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 2
    listener:
      #?enable.auto.commit?????false?????????true?????
      #manual_immediate:??????Acknowledgment.acknowledge()?????
      ack-mode: manual_immediate
      missing-topics-fatal: true #???????topic????true?????false??
      #type: single #?????????? #???????? consumer.max-poll-records
      type: batch
      concurrency: 2 #????????????????????????????????
    template:
      default-topic: "thermal_runaway_full_date_test"


